### ISSUE TITLE
Entity: translation request management

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#151]
Design and implement the user interface where entities receive translation requests and respond to them.

**Comment by cherylhjli** [comment]
Translation requests appear on the FRO dashboard: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1491%3A35377
Manage my translations page: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1287%3A15648
Manage translations for specific engagement: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1287%3A16238

**Comment by cherylhjli** [comment]
@greatislander close? We've created that workaround where the user can request another translation via email.
