### ISSUE TITLE
Browse disability organizations, advocacy groups, informal constituency groups

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#152]

**Comment by cherylhjli** [comment]
Browse community organizations: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1301%3A17738

Also agreed in discussion with Ned that we have browse pages for accessibility consultants and community connectors.
AC: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2221%3A61802
CC: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2221%3A62316

**Comment by cherylhjli** [comment]
@greatislander close? this seems covered under #311. We also don't have informal constituency groups or advocacy groups specifically called out on the platform.
