### ISSUE TITLE
Regulated organization: add existing user as member of regulated organization

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#153]

**Comment by cherylhjli** [comment]
Roles and permissions: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1796%3A52675

Invite new member: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1796%3A53694
