### ISSUE TITLE
Settings: roles and permissions

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#254]

**Comment by cherylhjli** [comment]
Main roles and permissions page:
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1796%3A52675

Edit a member's role and/or project: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1796%3A52764

Invite new member: 
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1796%3A53694
