### ISSUE TITLE
User: notification management page

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#255]

**Comment by cherylhjli** [comment]
Manage notificaitons:
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1266%3A14336

Notification contact method: 
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2351%3A62884

Notification list:
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2308%3A61319

**Comment by greatislander** [comment]
Duplicate of #578.
