### ISSUE TITLE
Community member: differentiate roles when creating pages

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#271]
https://docs.google.com/spreadsheets/d/1jTOgTo_N512S8jaYWSuLi_xJU8eH6ejCkQTNGs6eqiw/edit#gid=0

**Comment by cherylhjli** [comment]
This happens right after a community member completes sign up. They get a page with an intro video, and then they go to pick their role: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1491%3A33137
