### ISSUE TITLE
Community member: translation options for all fields

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#274]

**Comment by cherylhjli** [comment]
Same pattern as translation management for entities and community orgs, minus the central translation management page. They also don't get the language selection at the beginning of their profile creation flow. They can add a language directly in the language accordion.

https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1761%3A48525
