### ISSUE TITLE
Regulated organization: allow users to view and request to join an existing regulated organization if they attempt to create a duplicate

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#276]
- [ ] https://www.figma.com/file/35NiapHpSyGcZP24H2HWZF/Ideation-Co-design-wires?node-id=585%3A16967
- [ ] https://www.figma.com/file/35NiapHpSyGcZP24H2HWZF/Ideation-Co-design-wires?node-id=586%3A16985

**Comment by cherylhjli** [comment]
This has been moved up to the onboarding flow, where once a user signs up, they can immediately join a FRO or create a new FRO. Screens here: https://github.com/accessibility-exchange/platform/issues/457
