### ISSUE TITLE
Regulated organization: language selection during page creation

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#277]
https://www.figma.com/file/35NiapHpSyGcZP24H2HWZF/Ideation-Co-design-wires?node-id=544%3A17286

**Comment by cherylhjli** [comment]
Updated links:
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1125%3A17897
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1125%3A17922
