### ISSUE TITLE
Regulated organization: change/request language

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#288]

**Comment by cherylhjli** [comment]
Confirming that requesting language is out of scope now?
Does changing the language refer to a community member or organization viewing the entity's page in a different language?

**Comment by greatislander** [comment]
Correct, requesting is out of scope. Changing language scenario: the page is available in a language, e.g. Mandarin, Hindi, Inuktitut, that you can't switch the website to.

**Comment by cherylhjli** [comment]
Manage translations page is accessible thru the dashboard. Users can manage what languages are added to their entity page, project pages, and engagement pages. There are also settings on these pages individually - they should be consistent with the manage translations page.

Main page: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1287%3A15648
Specific engagement: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1287%3A16238 (can use the same for specific project)
Add language modal: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1856%3A53735
Remove language modal: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1856%3A53790
Successfully added language notification: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1856%3A54481

Managing translations within the edit state of a page (this example is the entity page, but can be applied to a project or engagement page) : https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1856%3A53821
Link from the view state of a page to manage translations, which takes you to the edit state of that page: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1856%3A54289

Community member view of the entity page: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1340%3A19798

Can switch languages
Can request language by emailing the FRO
