### ISSUE TITLE
Accessibility: Show ASL player

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-exchange/platform#308]

**Comment by cherylhjli** [comment]
Can turn it on in the web accessibility preferences page: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2265%3A74852

In-page it will show up as a button you can click to open and close the videos: 
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2327%3A63742
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2327%3A62233

**Comment by greatislander** [comment]
Duplicate of #496.
