### ISSUE TITLE
Design system / cards: engagement

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#373]

**Comment by cherylhjli** [comment]
For standalone engagement cards (not attached to project cards)...
- Hover state: grey 1 background, no drop shadow, grey 3 1px border, bottom line is 1 shade lighter (blue 5)
- Focus state: white background, blue 6 border 3px, drop shadow
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1397%3A22398
