### ISSUE TITLE
Resource page: view

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#394]
Align with Doris' resources.

**Comment by cherylhjli** [comment]
Each resource page can house many different formats and languages, including both internal and external files. They can switch on the resource page itself. However, each resource will have a primary format and language. This will be the format that shows up, unless the user has their language set to a language that the resources has a version in - in that case, the resource will be switched to that version.

https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2838%3A76275
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2838%3A76528
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2838%3A76892
