### ISSUE TITLE
Resource page: edit

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#401]

**Comment by cherylhjli** [comment]
Platform admin - manage resources:
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3449%3A99436

Individual resource: 
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3449%3A99706

This is essentially the resource page, but with the platform admin toolbar and with extra controls (edit, delete, remove from collection).

**Comment by cherylhjli** [comment]
Platform admin - manage resources:
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3449%3A99436

Individual resource: 
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3449%3A99706

This is essentially the resource page, but with the platform admin toolbar and with extra controls (edit, delete, remove from collection).

Add a resource to a collection: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3462%3A99923
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3462%3A100130
