### ISSUE TITLE
Resource collection: edit

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#403]

**Comment by cherylhjli** [comment]
Manage resources - collections: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3462%3A100385

Renaming a collection: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3462%3A101298

**Comment by greatislander** [comment]
Resolved in #1383.
