### ISSUE TITLE
Engagement: manage

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#407]
- [x] #616
- [x] #617
- [x] #618
- [x] #619
- [x] #620
- [x] #1128
- [x] #1129
- [ ] #1130

**Comment by cherylhjli** [comment]
For managing an engagement, the page will look different depending on the format and recruitment method.

- Format - workshop OR focus group, recruitment method - matching service
Manage engagement, empty state: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3326%3A99819
Manage engagement, filled in state: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3326%3A100033
Add engagement details - empty: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2612%3A66654
Add engagement details - meeting filled out: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2612%3A67417
Add new meeting: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2612%3A66872

Match to participants - step 1: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3220%3A99643
Match to participants - step 2: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3244%3A99771
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3244%3A99988
Match to participants - step 3: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3244%3A101335
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3244%3A101698

Manage participants - confirmed participants:
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2955%3A79154
Manage participants - access needs: 
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2733%3A75531
