### ISSUE TITLE
Engagement: viewing

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#408]

**Comment by cherylhjli** [comment]
Workshop/focus group + matching service
Public view: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2727%3A73265
Participants only: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2727%3A74124

Survey + open call
Public view: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2723%3A71437
Participants only: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2727%3A73024

Interview + CC
Public view: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2732%3A73670
Participants only: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2733%3A74754
Private, view by FRO: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2730%3A73293

Other - synchronous is going to look like the workshop/focus group page.
Other - asynchronous is going to look like the survey page.
