### ISSUE TITLE
Dashboard: Participant

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-exchange/platform#447]
For onboarding, have the following to fill out:
- Personal information (identity etc)
- Access needs
- Languages
- Payment info (acceptable formats)
- Contact info (including meeting types, support person)

Also include a way for someone to share projects or engagements with open calls

**Comment by greatislander** [comment]
See: https://github.com/accessibility-exchange/platform/issues/827

**Comment by jobara** [comment]
@cherylhjli, and @greatislander what is still needed for this?

**Comment by greatislander** [comment]
See comment on #457.

**Comment by michelled** [comment]
This is covered in the Getting Started Module https://github.com/accessibility-exchange/platform/issues/1444
