### ISSUE TITLE
Dashboard: Accessibility consultant & community connector

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-exchange/platform#449]
For onboarding, make sure user fills out:
- Public profile
- Contact info (including support person, meeting types)
- Languages

**Comment by cherylhjli** [comment]
Dashboard upon signing up: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1784%3A51410
Dashboard after a bit of usage: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1488%3A32892

Entering personal info / collaboration preferences: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1784%3A51670

**Comment by jobara** [comment]
@greatislander and @cherylhjli is this finished?

**Comment by greatislander** [comment]
See comment on #457.

**Comment by michelled** [comment]
This is covered in the Getting Started Module https://github.com/accessibility-exchange/platform/issues/1444
