### ISSUE TITLE
Entity: Dashboard

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-exchange/platform#457]
- Once they sign up
- After they've been using it for a bit

**Comment by cherylhjli** [comment]
Onboarding:
This includes the process of figuring out whether the user needs to create a new FRO, or can join one.
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1491%3A35938
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1507%3A34122
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1507%3A34286
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1507%3A34489

Dashboard for org admin:
Empty: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1491%3A35377
Filled in: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1856%3A51722

Dashboard for project admin:
Empty: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1491%3A35613
Filled in: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1856%3A52056

Dashboard for project member: 
Empty: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1494%3A33971
Filled in: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1856%3A52396

My trainings:
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1378%3A22421

**Comment by jobara** [comment]
@cherylhjli and @greatislander should this be closed in favour of specific tickets for the parts that need to be added/updated?

**Comment by greatislander** [comment]
I think all the dashboard tickets probably should be. I didn't do it because I figured best to let you and @cherylhjli and @michelled break it down and prioritize as needed. But in essence, the dashboards are missing the numbered onboarding steps for all roles.
