### ISSUE TITLE
Community Member: delete matching information and profile

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#481]
This is a bit more nuanced than #479 and #480 mainly because the `CommunityMember` model includes not just the public page but also the matching data. I think there's probably two pieces to this: 

- [ ] Delete matching information
- [ ] Delete public profile

If someone wants to do both there would be no way for them to use the platform other than to browse resources so maybe it might make sense for them to be offered the option to delete their whole account at that point.

@cherylhjli I think we'll need to talk this through but it doesn't need to happen until next week.

**Comment by cherylhjli** [comment]
Pause matching:
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2424%3A63650

Resume matching: 
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2424%3A64366

Delete matching info: 
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2424%3A64195

Delete public profile: 
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1540%3A36401

Confirm delete modal:
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2424%3A64519
