### ISSUE TITLE
Adjustable contrast

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#495]

**Comment by sepidehshahi** [comment]
When Dark mode is selected, the block organization modal doesn't show up with the right colours. 
<img width="1123" alt="Screen Shot 2022-08-11 at 11 00 25 AM" src="https://user-images.githubusercontent.com/10619898/184166473-606e0387-1a01-4afc-9bab-9dec8c9fe16d.png">

**Comment by greatislander** [comment]
Temporarily disable this feature pending cleanup of styles.
