### ISSUE TITLE
Update community connector constituency groups

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-exchange/platform#536]
- Combine the disability, deaf, and supporter group with the disability types group 
- Combine Indigenous group with Ethnoracial groups
- Combine gender and sexuality group with immigrant/refugee

https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1540%3A36401

**Comment by greatislander** [comment]
This was resolved in #566.
