### ISSUE TITLE
Verify email change for individual

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#590]
When an individual changes their email on their Communication and consultation preferences page or the Communication and consultation section of their public page, their new email address needs to be verified.

**Comment by cherylhjli** [comment]
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2308%3A62005
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3635%3A98597
