### ISSUE TITLE
When registering as community or regulated organization user, users shouldn't be forced to create a new organization

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#591]
This will allow them to accept their invitation to join an existing organization.

**Comment by cherylhjli** [comment]
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3715%3A94984

**Comment by cherylhjli** [comment]
When I registered as an FRO member invited by my FRO, the flow took me to create a new reg org. I clicked dashboard, and saw the invitation to accept or decline. I clicked accept. However I am still getting a prompt for creating my FRO page - but if I click that I get a 403 forbidden. 

I don't have this problem when registering as a comm org member by my comm org.
