### ISSUE TITLE
Add resource

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-exchange/platform#624]
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3449%3A100130
After you've added versions: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3449%3A101303
Editing a version: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=3476%3A101157

**Comment by chosww** [comment]
More copies to update from #1156
