### ISSUE TITLE
Clearer error message for missing about on organization page

### ISSUE THREAD

**Issue by michelled** [accessibility-exchange/platform#645]
When creating an organization page in step 1 if you do not fill in the about you get the following error message: 
The about.en field is required when about.fr is not present.
The about.fr field is required when about.en is not present.

**Comment by cherylhjli** [comment]
This has not been updated with the copy in the error message spreadsheet on the staging site.

**Comment by cherylhjli** [comment]
Please update the error message to: 
You must fill out the field "about your organization".
