### ISSUE TITLE
Individuals - Settings > Notifications: Success notification is cut off

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-exchange/platform#664]
After saving and the page refreshes, the success notification at the top is cut off.

**Comment by michelled** [comment]
@cherylhjli I just tried this with an individual page and didn't get the success message cut off. Can you put in detailed steps to reproduce?

**Comment by cherylhjli** [comment]
Sign in as individual > go to settings > notifications > change a setting > save

**Comment by cherylhjli** [comment]
<img width="1665" alt="Screen Shot 2022-08-04 at 3 28 46 PM" src="https://user-images.githubusercontent.com/9353905/182936998-60a80e8d-beec-4f17-80ce-1fafc3bff857.png">
<img width="1666" alt="Screen Shot 2022-08-04 at 3 29 01 PM" src="https://user-images.githubusercontent.com/9353905/182937006-e7d09687-8224-495f-a131-f1aa31067d21.png">
