### ISSUE TITLE
All users: Language accordion rename

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-exchange/platform#669]
Rename the language selection page before you go into the rest of the create a profile flow to: Profile translations
Rename the language accordion in edit mode to: Profile translations
Rename the language accordion in view mode to: Change profile language

**Comment by greatislander** [comment]
@cherylhjli: I notice you used profile here— I thought we were using "page" rather than "profile"? I realize the settings link also says "Public profile". I'm not sure if this has been changed by Aruna or if I should be using "page" and this issue (and the design for settings) is inaccurate.
