### ISSUE TITLE
FRO: "About your organization" French field is required despite removing french from language settings

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-exchange/platform#672]

**Comment by greatislander** [comment]
If the regulated organization type is "Government", there is a rule which always requires content in French and English. I'm wondering if this causes more confusion than it's worth? @cherylhjli @michelled Let's discuss.

**Comment by greatislander** [comment]
Discussed with @michelled — we will give Government orgs the same language options as others and not enforce French/English
