### ISSUE TITLE
Settings > Public profile link is broken

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-exchange/platform#679]
Steps to reproduce:

- in an account for the individuals go to the Settings
- In the settings "For consultations" select public profile

**Comment by michelled** [comment]
@sepidehshahi this worked for me - I was taken to my profile page - but I had already created it. What is happening for you when you select public profile?

**Comment by sepidehshahi** [comment]
@michelled I was trying to reproduce it today but the Public Profile link is already removed from the settings. So we can close this issue.

**Comment by greatislander** [comment]
Confirming, this is resolved.
