### ISSUE TITLE
All users: Create profile - social media links and wbesite links needs hint text to specify what format is accepted

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-exchange/platform#681]
I noticed the field only accepts URLs that start with "http://"

**Comment by greatislander** [comment]
Related: https://github.com/accessibility-exchange/platform/issues/562

**Comment by greatislander** [comment]
Can you give me an idea of what you think the hint text should be? http(s):// is now optional but I think it's still a good idea to give examples.

**Comment by cherylhjli** [comment]
Hint text: 

Website links must be in the format “http://www.example.com”, or “example.com”.
