### ISSUE TITLE
Increase table_definition_cache to ~2048

### ISSUE THREAD

**Issue by greatislander** [accessibility-exchange/platform#690]
I haven't tested this with the new local Docker branch yet so this may not be an issue on the Kube hosting. However, I'm working on a feature which depends on MariaDB/MySQL views and my local environment has been running into this error: https://jira.mariadb.org/browse/MDEV-17124

I resolved it by increasing the `table_definition_cache` to 2048.

We'll need to test this on the staging environment and make this change if it's required there.

**Comment by colleenskemp** [comment]
This is a maybe later ticket for now. Might not be an issue on the Kube infrastructure.

**Comment by marvinroman** [comment]
Increased `table_definition_cache` dynamically using the mysql command line on staging and production.
Created pull request #1143 to resolve permanently.
