### ISSUE TITLE
An individual account must have a role

### ISSUE THREAD

**Issue by michelled** [accessibility-exchange/platform#716]
Currently it is possible to create an individual account and not set a role.

**Comment by greatislander** [comment]
Tried this and it appears to prevent you from continuing without making a selection:
<img width="560" alt="Screen Shot 2022-08-09 at 12 35 46 PM" src="https://user-images.githubusercontent.com/605361/183695433-728edd51-947e-42f7-ba8c-0d80addab3a5.png">

**Comment by michelled** [comment]
@greatislander I'm able to go to the dashboard instead of selecting a role and then I can do things like look up the orgs etc. On my dashboard I do have an 'edit roles' link where I can add a role later.

**Comment by greatislander** [comment]
Oh, I see— sorry I hadn't understood the sequence. I'll reopen. It is going to cause issues if they don't select a role.
