### ISSUE TITLE
Registration: Sign language field is confusing

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-exchange/platform#720]
When creating an account, asking users to select a sign language without providing more context is confusing. 
https://tae-dev.inclusivedesign.ca/en/register

- [ ] change the field label from "Signed Language" to "Sign Language" 
- [ ] Add a description for this field to say if you use sign language select which sign language you prefer/use.

**Comment by cherylhjli** [comment]
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1269%3A15588
