### ISSUE TITLE
Individual page creation: phone number field kept showing an error

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-exchange/platform#726]
Individual page creation: step 4 communication and meeting preferences kept showing an Invalid phone number error
We tried a real 10 digit number starting with 416 as well as the same number starting with country code +1 and 01 but it didn't work and we got the error.

**Comment by greatislander** [comment]
This only happens when fake phone numbers are used, e.g. (416) 123-4567. Phone numbers in Canada never start with 123 so if one uses a real phone number this error won't occur.
