### ISSUE TITLE
Individual page creation (community connectors): Nested options can be confusing for screen reader users

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-exchange/platform#739]
When creating an individual page for community connectors and selecting groups they can connect to, there are several questions that have nested options. Although those questions are marked as required, the nested options are not. So, the user may skip selecting the nested options and as a result get an error message. 

We need to add instruction right before those nested options, such as "Please make sure to choose one of these options"

**Comment by cherylhjli** [comment]
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2613%3A68551

**Comment by cherylhjli** [comment]
I also updated these screens for community organizations too according to this feedback, as well as tweaked the copy of the original questions a bit:
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2560%3A65260
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2602%3A68633
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2567%3A65306
